---
include:
  - board: seeeduino_xiao_ble
    shield: "zonkey_R rgbled_adapter"
  - board: seeeduino_xiao_ble
    shield: "zonkey_L rgbled_adapter"
  - board: seeeduino_xiao_ble
    shield: settings_reset
